name: Deploy

on:          
  push:       # it can be on push or workflow_dispatch manually
    branches:
      - deployment # it can be any other branch name 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x  # Use preferrable node version

      - name: Install node modules
        run: |
          npm install

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name : Assemble with Gradle
        run: cd android &&  ./gradlew clean && ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }} # SIGNING_KEY from Github Secrets
          alias: ${{ secrets.ALIAS }} # ALIAS from Github Secrets
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }} # KEY_STORE_PASSWORD from Github Secrets
          keyPassword: ${{ secrets.KEY_PASSWORD }} # KEY_PASSWORD from Github Secrets

      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json # SERVICE_ACCOUNT_JSON from Github Secrets. its a json file containing information of Google Cloud Platform


      - name: Deploy to Alpha   
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.myApp #App package name
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: alpha  #can be other tracks like Production, Internal Testing etc
          whatsNewDirectory: distribution/